[package]
name = "viewu"
version = "0.2.0"
edition = "2024"

description = "A terminal based file format viewer made for DOCX in mind."
license = "MIT"

[dependencies]
anyhow = "1"
quick-xml = "0.38"
ratatui = "0.29"
crossterm = "0.29"
zip = "4"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
unicode-width = "0.1"
clap = { version = "4.6.1", features = ["derive"] }
pulldown-cmark = "0.13.4"
directories = "5"
rust-embed = "8"
